var GAME_LEVELS = [
  ["                               xx!!!!!xx                                                                          ",
   "                                xxxvxxx                                                                           ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                         J                                         ",
   "                                                         x =  x        xxxxx                                      ",
   "                                                      x          x            SS  SS                     xxxxxxxxx",
   "                                     xxx             x           |x           xx  xx                      xxxxxxx ",
   "                                                     x    x  x    x                                        xxxxx  ",
   "                                                     x            x                                         xxx   ",
   "                               xxx                   x            x           SS  SS                         x|   ",
   "                                                     x   x  = x   x           xx  xx                              ",
   "                                     xxx             x            x                                               ",
   "                                                     x            x                                              ",
   "                                                     x    x  x    x           SS  SS                              ",
   "                               xxx                   x|           x           xx  xx                              ",
   "                                                      x          x                                           o    ",
   "                                                         x =  x                                             |x    ",
   "                      xxxSSSxxx                                                                             xxx   ",
   "                xxx     xxxxx                                                                              xxxxx  ",
   "    @     xxx                                            xxxxxx                           xxSSSSSxx       xxxxxxx ",
   "  xxxxx                                          xxxxx                        xxxxxx    xxxxxxxxxxxxx    xxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                         x                 x                                                      ",
   "                                        xx                 xx                                                     ",
   "                                        xx        @        xx                                                     ",
   "                                        xx       xxx       xx                                                     ",
   "                                        xx      xxxxx      xx                                                     ",
   "                                        xx      xxxxx      xx                                                     ",
   "                                        xx=     xxxxx     =xx                                                     ",
   "                                        xx     =xxxxx=     xx                                                     ",
   "                                         x      xxxxx      x                                                      ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                        xxxxxxxx!!!!!xxxxxxxx                                                     ",
   "                                         xxxxxxxxxxxxxxxxxxx                                                      ",
   "                                  J               v               J                                               ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                       xSSSSx                                           xSSSSx                                    ",
   "                      xxxxxxxxxxx!!!!!!!!xxxxxxx!!!!!xxxxxxx!!!!!!!!xxxxxxxxxxx                                   ",
   "                                xxxxxxxxxx xxxxxx!!!xxxxxx xxxxxxxxxx                                             ",
   "                                     v      xxxxxxxxxxxxx      v                                                  ",
   "                                             xxx     xxx                                                          ",
   "                       xxxxxx                                           xxxxxx                                    ",
   "                      x xxxx   x                  o                  x   xxxx x                                   ",
   "                xxSSxx   xx      x              xxxxx              x      xx   xxSSxx                             ",
   "               xxxxxx              xxxxx  xxxxxxxxxxxxxxxxx  xxxxx              xxxxxx                            ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                x            x                                                ",
   "                                               xxx          xxx                                               ",
   "                                              xxxxx        xxxxx                                              ",
   "                                             xxxxxxx!!!!!!xxxxxxx                                             ",
   "                                            xxxxxxx!!!!!!!!xxxxxxx                                            ",
   "                                           xxxxxxx!!!!!!!!!!xxxxxxx                                           ",
   "                                          xxxxxxxx|x xxxx|x xxxxxxxx                                          ",
   "                                        xx                          xx                                        ",
   "                                      xx                              xx                                      ",
   "                                    xx                                  xx                                    ",
   "            x     x     x     x   xx                                      xx   x     x     x     x            ",
   "           x x   x x   x x   x xxx                                          xxx x   x x   x x   x x           ",
   "          xx xxxxx xxxxx xxxxx xx                                            xx xxxxx xxxxx xxxxx xx          ",
   "            |           |                 xxSSSxx     xx     xxSSSxx                 |           |            ",
   "                                        xxxxxxxxx   |      | xxxxxxxxx                                        ",
   "  @               |           |       xxx      xx!!!!!!!!!!!!xx      xxx       |           |               o  ",
   "xxxxx     xx xxxxx xxxxx xxxxx xxxxxxxx         xxxxxxxxxxxxxx         xxxxxxxx xxxxx xxxxx xxxxx xx     xxxxx",
   " xxx       x x   x x   x x   x x                                              x x   x x   x x   x x       xxx ",
   "  x         x     x     x     x                                                x     x     x     x         x  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                       x    x xxxxx x               x  x   xx ",
   "                                                                       xx   x   x   x               x x   x   ",
   "                                                                       x    x   x   xxx   xx    xx  xx     x  ",
   "                                                                       x   xx   x   x  x x  x  x  x x x     x ",
   "                                                                       x    x   x   x  x  xx x x  x x  x  xx  ",
   "                                                                       xx   x                                 ",
   "                                                                       x    x        xx                       ",
   "                                                                       x   xx       x                         ",
   "                    @                    J                             x    x      xxx  x   xx                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x                        xx   x       x  x x x                  ",
   "                                         x   xx                        x    x       x   x  x                  ",
   "                                       x x    x                        x   xx                                 ",
   "  x   x                         x      x xx   x                        x    x  xxx  x     x   x x       xxx   ",
   "   x x          x            x         x x    x                        xx   x x   x x      x x      o  x   x  ",
   "    x  x  x  x   x    xx    x   x  xx  x x   xx                        x    x x xx  x  xx   x   x  xx   xxx x ",
   "    x x x x  x    x  x  x  x    x x  x   x                                 xx x     x x  x  x   x x  x      x ",
   "    x  x  xxxx     xx    xx     x x  x x x                                  x x     x  xx x x   x x  x  xxxx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
